name: CI — develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build and run backend tests
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw -B test

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci
      - name: Install Chromium for headless tests
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Run frontend tests
        working-directory: frontend
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
